version: '3.4'

services:
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*
    volumes:
      - sqlser_volume:/var/opt/mssql
    ports:
      - "1433:1433"
  egebilgibilisimtask.webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
  egebilgibilisimtask.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5010:80"